const authModule = (await import('firebase/auth')) as typeof import('firebase/auth');

const {
  applyActionCode,
  beforeAuthStateChanged,
  browserLocalPersistence,
  connectAuthEmulator,
  createUserWithEmailAndPassword,
  getAuth,
  getRedirectResult,
  inMemoryPersistence,
  indexedDBLocalPersistence,
  initializeAuth,
  onAuthStateChanged,
  PhoneAuthProvider,
  RecaptchaVerifier,
  sendEmailVerification,
  sendPasswordResetEmail,
  signInWithEmailAndPassword,
  signInWithPopup,
  signOut,
  updatePassword,
  updateProfile,
} = authModule;

export {
  applyActionCode,
  beforeAuthStateChanged,
  browserLocalPersistence,
  connectAuthEmulator,
  createUserWithEmailAndPassword,
  getAuth,
  getRedirectResult,
  inMemoryPersistence,
  indexedDBLocalPersistence,
  initializeAuth,
  onAuthStateChanged,
  PhoneAuthProvider,
  RecaptchaVerifier,
  sendEmailVerification,
  sendPasswordResetEmail,
  signInWithEmailAndPassword,
  signInWithPopup,
  signOut,
  updatePassword,
  updateProfile,
};

export type {
  ActionCodeSettings,
  Auth,
  AuthCredential,
  AuthError,
  AuthProvider,
  ConfirmationResult,
  IdTokenResult,
  PhoneAuthCredential,
  PhoneInfoOptions,
  PhoneMultiFactorAssertion,
  RecaptchaParameters,
  SignInMethod,
  Unsubscribe,
  User,
  UserCredential,
} from 'firebase/auth';
