export {
  SUPER_ADMIN_PERSONAL_ID,
  SUPER_ADMIN_CONFIRMATION_HEADER,
  normalizeClaims,
  extractExpressClaims,
  extractFastifyClaims,
  isSuperAdmin,
  requireRole,
  allowSuperAdmin,
  hasSuperAdminConfirmation,
  type GuruloClaims,
  type GuardAuditEvent,
  type GuardAuditHook,
  type GuardOptions,
  type ExpressGuard,
  type FastifyGuard,
  type GuruloRequireRole,
  type GuruloAllowSuperAdmin,
} from './gurulo.auth.ts';
