name: Firebase Hosting Auto Deploy (Merge Trigger)

on:
  push:
    branches:
      - main
      - development

jobs:
  firebase_auto_deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy to Firebase Hosting

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Build frontend
        run: npm run build --workspace ai-frontend --if-present

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "🚀 Deploying build to Firebase Hosting..."
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"

      - name: Verify Deployment
        run: |
          echo "🔍 Checking hosting status..."
          firebase hosting:sites:list --project ${{ secrets.FIREBASE_PROJECT_ID }}
          echo "✅ Deployment complete for branch ${{ github.ref_name }}"

      - name: Notify (optional)
        if: always()
        run: |
          echo "📢 Deployment notification..."
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Timestamp: $(date --utc)"
